name: CI/CD Pipeline

on:
  push:
    branches:
      - main # Executa sempre que houver um push na branch main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  sonar:
    name: Quality Analysis
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: SonarQube Scanner
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
          npx sonar-scanner \
            -Dsonar.projectKey=joaomrpimentel_j-lib-calc \
            -Dsonar.organization=joaomrpimentel \
            -Dsonar.sources=src \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN

  publish:
    name: Publish to npm
    runs-on: ubuntu-latest
    needs: [test, sonar]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npm install

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public

      # - name: Send notification to Discord
      #   if: success()
      #   run: |
      #     curl -H "Content-Type: application/json" \
      #       -d '{"content": "📦 A new version of **j-lib-calc** has been published on npm!"}' \
      #       ${{ secrets.DISCORD_WEBHOOK_URL }}
